- name: Install Nessus Agent on Linux Servers
  hosts: "{{ target }}"
  become: yes
  vars:
    nessus_key: XXXXXXXXXX
    agent_group: XXXXXX
    agent_host: XXXX
    agent_port: XXXXX
    agent_file_src: /tmp/nessus/CM-295445_NessusAgent-10.4.1-es7.x86_64.rpm
  tasks:
  - name: Check link status
    shell: /opt/nessus_agent/sbin/nessuscli agent status; true
    register: nessus_link_status

  - name: Check Nessus Agent Service Status
    shell: service nessusagent status; true
    register: nessus_agent_service_status
 
  - name: Install Nessus Agent rpm from a local file
    yum:
      name: "{{ agent_file_src }}"
      state: present
    when: "'Linked to: {{ agent_host }}' not in nessus_link_status.stdout"

  - name: Link nessus agent to tenable
    shell: >
      /opt/nessus_agent/sbin/nessuscli agent link 
      --host={{ agent_host }} 
      --port={{ agent_port }} 
      --key={{ nessus_key }} 
      --groups={{ agent_group }}
    when: "'Linked to: {{ agent_host }}' not in nessus_link_status.stdout"
  
  - name: Ensure Nessus Agent is started
    service:
      name: nessusagent
      state: started
      enabled: yes
    when: "('Linked to: {{ agent_host }}' not in nessus_link_status.stdout) and ('active (running)' not in nessus_agent_service_status.stdout)"

  - name: Verify Nessus is Running
    #command: service nessusagent status
    systemd:
      name: nessusagent
    register: nessus_status
